### YML file
services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    container_name: n8n-server  # Custom container name
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - ./n8n-data:/home/node/.n8n
